import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>My Navbar</h1>
          <div>
            <Link href={'/'} >Back to Home</Link>{' * '}
            <Link href={'/users'} >Users</Link>{' * '}
            <Link href={'/about'} >About</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
